version: '3.9'
services:
  job-application:
    build:
      context: .
      dockerfile: Dockerfile.shell
      target: dockershell
      args:
        NODE_VERSION: 16
    image: job-application
    hostname: job-application
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    working_dir: /app/jobapplication
    depends_on:
      - db
    volumes:
      - ./:/app/jobapplication/:z
      - ~/.npmrc:/root/.npmrc:z
      - ~/.npmrc:/home/node/.npmrc:z
      - ~/.npm/:/home/node/.npm/:z
      - '${SSH_AUTH_SOCK:-/tmp/_ssh_auth_sock_stub}:${SSH_AUTH_SOCK:-/tmp/_ssh_auth_sock_stub}'
    ports:
      - 3010:3010
      # NodeJS debug ports
      - 9222:9222
      - 9229:9229
    environment:
      SSH_AUTH_SOCK: '${SSH_AUTH_SOCK:-/tmp/_ssh_auth_sock_stub}'
      APP_DB_HOST: 127.0.0.1
      APP_DB_PORT: 5432
      APP_DB_USER: postgres
      APP_DB_PASS: postgres
      APP_DB_NAME: job_application_dev
    stdin_open: true
    tty: true

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invoice_app
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - 54045:5432
