name: pipeline

on: [push]

# !!! IMPORTANT !!!
# this pipeline also requires a secret
# the secret is a personal access token
# called 'PIPELINE_PAT'
# used in the build-package job
env:
  PACKAGE_REGISTRY: 'ghrc.io'
  PACKAGE_AUTHOR: 'pscldev'
  PACKAGE_NAME: 'job-application-backend-test'

jobs:
  build-lint-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Get yarn cache directory path 🛠
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache node_modules 📦
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies 📦
        run: yarn

      - name: Run linter 👀
        run: yarn lint

  build-package:
    if: github.ref == 'refs/heads/master'
    needs: [build-lint-and-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.PIPELINE_PAT }}

      - name: Login to registry 🔐
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.PACKAGE_REGISTRY }}
          username: ${{ github.ACTOR }}
          password: ${{ secrets.PIPELINE_PAT }}

      - name: Backend - Build and push image 🚀
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v3
        with:
          push: true
          context: './'
          file: './Dockerfile'
          tags: ghcr.io/pscldev/job-app-backend:test
          build-args: |
            DOCKER_TAG=${{ steps.semantic.outputs.new_release_version }}
